language: node_js

node_js:
  - node
  - lts/*
  - 10
  - 9
  - 8

os:
  - linux

sudo: false

notifications:
  email: false

stages:
  - style
  - test
  - deploy

jobs:
  include:
    - stage: style
      script:
        # check code style according to StandardJS
        - npm run check:style

    - stage: test
      script:
        # run tests with coverage
        - npm run check:coverage

      after_success:
        # submit coverage report
        - npx nyc report --reporter=text-lcov > coverage.lcov && npx codecov

    - stage: deploy
      script:
        # list the files that will be released
        - npm pack --dry-run

      deploy:
        skip_cleanup: true
        provider: script
        script:
          # - npx semantic-release
