language: node_js

node_js:
  - node
  - lts/*
  - 10
  - 9
  - 8

os:
  - linux
  - osx
  - windows

sudo: false

notifications:
  email: false

cache:
  npm: true

stages:
  - style
  - test
  - deploy

jobs:
  include:
    - stage: style
      script:
        - npm run style:check

      after_success:
        # submit coverage report
        # - npx nyc report --reporter=text-lcov | npx coveralls

    - stage: test
      script:
        - npm test

      after_success:
        # submit coverage report
        # - npx nyc report --reporter=text-lcov | npx coveralls

    - stage: deploy
      script:
        # restructure the package, then list the files that will be released
        # - rm index.js            # remove files in project root
        # - rm -rf docs tasks test # remove directories
        # - mv src/* .             # move code to the project root
        # - rm -rf src             # remove previous code directory
        # - npm pack --dry-run     # list the files

      deploy:
        skip_cleanup: true
        provider: script
        script:
          # - npx semantic-release
