language: node_js

node_js:
  - node
  - lts/*
  - 10
  - 9
  - 8

cache:
  npm: false

os:
  - linux

sudo: false

notifications:
  email: false

stages:
  - test
  - style and coverage
  - name: deploy
    if: branch = master

jobs:
  include:
    - stage: style and coverage
      script:
        # check code style according to StandardJS
        - npm run check:style

        # run and check tests with coverage
        - npm run check:coverage
        - npm run check:coverage
        - npx nyc check-coverage

      after_success:
        # submit coverage report
        - npx nyc report --reporter=text-lcov > coverage.lcov && npx codecov

    - stage: deploy
      deploy:
        skip_cleanup: true
        provider: script
        script:
          - npx semantic-release
