language: node_js

os:
  - linux

sudo: false

notifications:
  email: false

node_js:
  - node
  - lts/*
  - 10
  - 9
  - 8

cache:
  # disable NPM cache to prevent "The command "eval npm ci" failed 3 times." issue
  # more: https://github.com/travis-ci/travis-ci/issues/10113
  npm: false

stages:
  - test
  - style and coverage
  - name: deploy
    if: branch = master

jobs:
  include:
    - stage: style and coverage
      script:
        # check code style according to StandardJS
        - npm run check:style

        # run and check tests with coverage
        # second run workaround - https://github.com/istanbuljs/nyc/issues/993#issuecomment-468265881
        - npm run check:coverage > /dev/null 2>&1
        - npm run check:coverage

        # enforce 100% coverage check
        - npx nyc check-coverage

      after_success:
        # submit coverage report
        - npx nyc report --reporter=text-lcov > coverage.lcov && npx codecov

    - stage: deploy
      deploy:
        skip_cleanup: true
        provider: script
        script:
          - npx semantic-release
